### ISSUE TITLE
Qual  o fluxo correto de uma venda?

### ISSUE THREAD

**Issue by Ronierys2** [adrbarros/CliSitef#1]
esses dias baixei seu projeto para tentar fazer essa implementação em C# com WPF até ai tudo bem, mas percebir que ele só pede as parcelas ou se é avista o cartão depois de ter passado o cartão no pinpad! 
isso esta certo ?

não deveria ter que informar essas coisas antes e quando passar o cartão já ser somente para finalizar ?

**Comment by adrbarros** [comment]
Boa tarde, nas Opções de pagamento via Crédito, vai aparecer a opção a vista ou parcelado já com o cartão inserido no PIN-PAD quando o mesmo é Chipado. Agora se o cartão não for chipado e aceitar somente passagem pelo magnético a resposta é sim vai pedir essa ação após passar o cartão pelo magnético.

Existe também configuração de parcelamento por Débito, ai isso é no próprio Gerenciador do Sitef
![ParcelamentoCartaoDebito](https://user-images.githubusercontent.com/15065213/139727997-24efbde2-2717-4777-b902-eee3297d8703.png)

**Comment by Ronierys2** [comment]
show !!

já até terminei a homologação !!

mas goste muito da sua resposta, foi bem esplicado valeu !!
