### ISSUE TITLE
Alterar valor da venda

### ISSUE THREAD

**Issue by bruno-crr** [adrbarros/CliSitef#11]
Boa tarde, estou precisando implementar uma rotina que altere o valor da venda após a leitura e identificação do cartão, no caso uma determinada bandeira poderia conceder desconto na venda;

Eu uso a sua aplicação como base para o meu TEF, seria possível fazer esse tratamento? Vi que o comando 154 seria para alterar o valor da venda, mas sempre que altero o valor da venda ele me retorna erro no PIN PAD;

**Comment by adrbarros** [comment]
Bom dia, Acrescentei o TipoComado 154 -> Contém o novo valor de pagamento. Eu não tenho esse processo em Nenhum Cliente, então nao sei se está correto. Se tiver como testar, ou me orientar como fazer isso na Aplicação de Testes, eu agradeço.

**Comment by bruno-crr** [comment]
Bom dia, eu vi aqui como vc, eu tava tentando fazer diferente, estava tentando usar o Comando 34 que retorna um formulario Currency e ai sim adicionar o obj3 substituindo o que já existia, mas de toda forma não estou conseguindo encaixar a lógica dentro da aplicação de como criar esse desvio nos casos necessários também, eu tique adicionar uma diretiva no CliSitef.ini
[Geral]
TransacoesAdicionaisHabilitadas=7;8;16;20;26;27;29;30;37;38;40;42;43;3014;3985
PermiteAlterarValorPagamento=1

Mas aparentemente quando está habilitado ele sempre cai no Comando 34, entao eu capturo o valor adiciono aos retornos mas ai a transação retorna erro de PIN PAD, se o usuário confirmar o valor mantendo o original a transação conclui sem erros

**Comment by adrbarros** [comment]
Correção aplicada, faça o teste! Será retornado no aquivo de dados da Transação na posição 003-010 o valor alterado

**Comment by bruno-crr** [comment]
Fiz o teste na sua aplicacao de teste e ela retorna o mesmo erro da minha ERRO PIN PAD, segue o print

![asdfa](https://github.com/adrbarros/CliSitef/assets/52460702/87989e86-007c-4b1a-abdb-b672ab3d4e4e)

**Comment by adrbarros** [comment]
Acho q pode ser algum problema no PinPad ou cargas de Tabelas, porquê, nos meus testes aqui deu tudo certo
mande seu e-mail para eu encaminhar um Video

[TefCrt_097749_T001_20240118110048.txt](https://github.com/adrbarros/CliSitef/files/13977482/TefCrt_097749_T001_20240118110048.txt)

**Comment by bruno-crr** [comment]
opa bruno.carvalho@msn.com , pode ser algo no meu servidor de demo que faz muito tempo que foi instalado, e nao tem gerado carta pro pin pad, vou tentar reinstalar ele, outra coisa, esse comando ele faz automático mesmo né, quando habilita a diretiva no ini ele vai sempre passar pelo comando 34

**Comment by adrbarros** [comment]
Mandei um Link para Você

**Comment by bruno-crr** [comment]
opa vlw, eu vi aqui o video e vi que vc usou cartao inserido, eu estava testando com aproximacao via celular, com o cartao fisico inserindo no pin pad realmente funcionou o fluxo, o erro ocorre apenas com o uso de aproximação ele deve ter um fluxo diferente

**Comment by adrbarros** [comment]
Encaminhei o DMP para FiServ Software Express (Via SkyTEF), para analisarem e ver se é erro na Aplicação ou da Dll CliSitefI.dll,
Ficarei no Aguardo da resposta Deles

**Comment by bruno-crr** [comment]
Boa tarde, obrigado ai pela força ajudou bastante até aqui!!

**Comment by bruno-crr** [comment]
Bom dia tudo bem? o pessoal da Skytef retornou pra vc? Eu enviei email pro suporte deles também mas até agora não tive resposta.

**Comment by adrbarros** [comment]
Sim, responderam que estão fazendo os testes junto a SoftwareExpress. O Suporte Desenvolvimento SkyTEF entrou em contato, conectaram no meu PC, viram fazendo os procedimentos das 2 formas etc

**Comment by bruno-crr** [comment]
Opa blz, obrigado ai , vou aguardar ver se eles te dão um retorno

**Comment by bruno-crr** [comment]
Boa noite, o pessoal conseguiu identificar o seu contato, o meu não conseguiram ver nada pelo DMP, falaram que a dll era uma versão antiga e talvez possa ser isso, mas ainda não conseguiram passar nada de concreto

**Comment by adrbarros** [comment]
Resposta, até o momento recurso habilitado somete para inserção do cartão, por aproximação recurso ainda não liberado.

**Comment by bruno-crr** [comment]
Bom dia, ok vou tentar ver em qual comando diferencia a aproximacao pra desabilitar o recurso que ativei
