### ISSUE TITLE
Coletar Cpf do consumidor pinpad

### ISSUE THREAD

**Issue by FanturySoftware** [adrbarros/CliSitef#12]
Olá, 

Estou executando esse projeto a função de obter o cpf do consumidor no pinpad, e estou obtenho um erro. Estou usando um pinpad da gertec ppc920, as outras funções de vender com cartao de credito/debito esta sendo executado perfeitamente.

A minha duvida se tem algo a mais para ser configurado no sitef demo ou no clisitef.ini, ou se é presciso de alguma outra dll para que eu possa obter o cpf pelo pinpad.

Desde já agradeço.

**Comment by adrbarros** [comment]
Olá, bom primeiro preciso saber qual erro esta sendo apresentado.
O pinpad deve estar habilitado para criptografia ABECS
