### ISSUE TITLE
Documentaçao DLL

### ISSUE THREAD

**Issue by Marlonwg** [adrbarros/CliSitef#13]
Existe alguma documentaçao sobre essa DLL eo programa cli-sitef converti ele do C# para o vb.net mas queria saber se tem algo relacionado a explicar melhor o codigo.

**Comment by adrbarros** [comment]
Ola, no projeto tem toda a Documentação da Software Express, explicando o Fluxo dos processos para Transação Eletrônica de Fundos (TEF), é o necessário para conhecimento do Fluxo. Porém a implementação é o Básico para o Funcionamento em um Estabelecimento, a fim de recebimento dos valores em Cartões.

Obs.: Após implementação em seu projeto, deve ser realizado Homologação junto a SoftwareExpress, para liberação de sua solução pra Produção (Existe um Roteiro para Testes, que se encontra na pasta Documentação)
