### ISSUE TITLE
Erro de CliSiTef32.dll não encontrada.

### ISSUE THREAD

**Issue by guilhermewalter** [adrbarros/CliSitef#14]
Quando vai compilar o projeto esta dando erro quando vai abrir:
![image](https://github.com/adrbarros/CliSitef/assets/13858646/17016dd6-3940-4a10-a5d0-53677f2d45aa)

**Comment by adrbarros** [comment]
Ola, você tem q adicionar as DLLs que estão em src\ExternalLibraries\TEF_Demo_DLLs, na pasta do seu Executável

**Comment by guilhermewalter** [comment]
Deu certo agora, essas dll tem alguma atualização frequentemente? vocês mesmos disponibilizam quando tem versão mais nova ou tem em algum local para baixarmos?
Obrigado.

**Comment by adrbarros** [comment]
Eu, quando lembro, procuro sempre deixar atualizado (porém para Ambiente de Homologação)
Atualizações, DLL e Documentação, existe tudo no ambiente da SoftwareExpress, para isso você deve entrar em contato com os mesmo, ou com uma empresa chamada SkyTEF (que pertence a Fiserv, que tb é dona da SoftwareExpress), para realizar testes de homologação no seu Software e afim de solicitar acesso ao portal
