### ISSUE TITLE
Sobre o QRCODE

### ISSUE THREAD

**Issue by Marlonwg** [adrbarros/CliSitef#15]
Boa noite sobre o codigo do QRCODE quando gera no botao CRT CD ele da erro -27 isso acontece porque esta em modo homologado ? nao funciona o modo carteira digital qual modo qrcode ?

**Comment by adrbarros** [comment]
Funciona em Homologação, SIM.

![0-Gereciador_TEF](https://github.com/adrbarros/CliSitef/assets/15065213/385e3aa6-2405-4ad8-8301-8d14a0e7c3bf)

Você configura ele apontado para o Mercado Pago.

Depois é so seguir o processo de configuração do modulo CardSE Homologação
Documentos: 
5-CardSE_Guia de Instalação.pdf
8-CardSE_PIX_Guia de Instalação.pdf

**Comment by Marlonwg** [comment]
Vlw vou testar obrigado.
