### ISSUE TITLE
TipoCampo 147 Valor a ser cancelado

### ISSUE THREAD

**Issue by diegobittencourt** [adrbarros/CliSitef#16]
Recentemente a a SiTef implementou essa Valor a ser Cancelado em situações onde pode existir cancelamento parcial do valor pago, gostaria de saber onde devo implementar na solução essa situação ?

Atualmente o log da aplicação aponta esse comando e tipo de campo travando o sistema e aumentando o tamanho do log:

-> Cmd: 34 -> Tc: 147 -> Buffer: Valor do cancelamento

**Comment by adrbarros** [comment]
Ola, ainda não vi esse recurso de cancelamento parcial. Pelo menos na Lib ainda nao existe essa implemetação
me mande o Log e como simulou isso

**Comment by diegobittencourt** [comment]
[Log20240411.txt](https://github.com/adrbarros/CliSitef/files/15044912/Log20240411.txt)

Tratasse de uma situação em ambiente de produção, solicitei junto a Sitef como simular essa situação no ambiente de homologação e ainda não obtive retorno.

**Comment by adrbarros** [comment]
Fiz um Ajute ai para Captura do Valor. Como não sei testar essa situação, terá que atualizar o Cliente e fazer o teste em produção.

Atualizar as DLLs e olhar na sua Rotina onde colocou um código similar a esse ai:
![image](https://github.com/adrbarros/CliSitef/assets/15065213/dfb4985d-7af3-4c14-b7f6-dcd31b0bc6ea)
