### ISSUE TITLE
Problema na conexao Com maquina API CRedito

### ISSUE THREAD

**Issue by Marlonwg** [adrbarros/CliSitef#17]
Estou com um problema com a maquina da GERTEC PPC930 quando em homologação na função debito passa de boas
agora na função credito quando uso ela e pede a senha ele diz opçao recusada pelo cartao ?
Tem alguma configuração pra fazer na maquina ou e assim mesmo ?

**Comment by adrbarros** [comment]
Bom na instalação padrão para ambiente homologação, existe alguns detalhes onde alguns cartões vêm bloquedos justamente para fazer testes. Tipo no meu caso aqui passa MasterCard Credito/Debito, Visa Credito normalmente. Visa Debito, ELO Debito/Credito não passam dando mensagem Transação negada ou recusada pela Administradora.

Acho que isso é comum, para fazer testes.

Porém sei que existe algumas configurações em arquivos e módulos, que libera. Mas nunca dei muita bola para isso.

**Comment by Marlonwg** [comment]
Assim entendi vou tentar com outro cartao pra verificar essa questão obrigado.

**Comment by Marlonwg** [comment]
Resolvido usei um nubank passou normal obrigado adrbarros

Uma ultima duvida na homologação e producao eo mesmo codigo oque muda sao apenas as dll's 
vou usar somente opçao debito e credito.

**Comment by adrbarros** [comment]
![image](https://github.com/adrbarros/CliSitef/assets/15065213/98170feb-ee6c-4c12-8300-36b5dba31f0a)
 
No projeto vão as DLLs para Ambiente Homologação (TEF Simulado).

Quando sua solução for para uso em Produção no Clente, você deve solicitar o baixar essas mesmas DLLs (porém para Produção). Muda somente essas DLLs
