### ISSUE TITLE
Como fazer parcelamento no cartao de credito?

### ISSUE THREAD

**Issue by dionathanbatista** [adrbarros/CliSitef#18]
Olá.
Primeiramente muito obrigado sua solução me ajudou muito.
Segundo, tenho uma duvida, como faço para parcelar no cartão de credito?

**Comment by adrbarros** [comment]
Retire essa linha do seu Arquivo Clisitef.ini:
TransacoesDesabilitadas=17;18;19;27;28;36;44;3031;3227;3480;3988;3989;
ou coloca um ; no inicio dela
;TransacoesDesabilitadas=17;18;19;27;28;36;44;3031;3227;3480;3988;3989;

Consultar o:
0-SiTef - Interface Simplificada com a aplicação(VRS-253).pdf 
(pag 95)
6.19 Tabela de códigos de meios de pagamento, configurações e menus

Serve para:
TransacoesAdicionaisHabilitadas
e
TransacoesDesabilitadas

**Comment by dionathanbatista** [comment]
Perfeito perfeito deu certo aqui aparece para selecionar.
Uma outra duvida seria como faço para o sistema ja enviar essas informações para que o usuario nao precise mecher teria como?

**Comment by adrbarros** [comment]
Não sei responder, creio que você devera ligar no Suporte Desenvolvimento deles para obter essa informação, pois, eu nunca precisei fazer isso.

**Comment by dionathanbatista** [comment]
Valew, muito obrigado agradeço de coração
