### ISSUE TITLE
QR Code no Pin Pad

### ISSUE THREAD

**Issue by EmersonI22** [adrbarros/CliSitef#2]
Bom dia, estava estudando o Projecto para implementar integração com outra linguagem de programação. 
Estou com dificuldade para testar Qr Code para pagamento com carteira digital no 'Pin Pad Gertec PPC930'. 
Em pesquisa pela web ele suporta QR-Code no visor do Pin Pad. 
Fonte pesquisa QR-Code Pin Pad PPC930: https://loja.gertec.com.br/produto/ppc930/#

No Projeto está sendo passado o ParamAdic = ”DevolveStringQRCode=1” na rotina IniciaFuncaoSiTefInterativo. 
No arquivo CliSiTef.ini [PinPadCompartilhado] Porta=AUTO_USB. 
Está tudo certo com o meu ambiente, tanto que funciona o pagamento com cartão de crédito no Pin Pad. O que eu estou fazendo de errado. Tem alguma dica?

**Comment by adrbarros** [comment]
no aquivo App.config
add key="Tef_PinPadQrCode" value="1"

Lembrando que a versão do Firmware do PinPad deve ser 2.08 ou Superior

Quando: add key="Tef_PinPadQrCode" value="0", sera devolvida a string {DevolveStringQRCode=1} nos parametros adicionais para geração do QrCode na tela do PC

**Comment by EmersonI22** [comment]
Muito obrigado pela ajuda Adriano, mas infelizmente não consegui resolver ainda.
Fiz os ajustes como sugerido app.Config coloquei “1” no value do Tef_PinPadQrCode
Estou desconfiado a versão do Firmware que você comentou mais não descobri ainda como obter esta informação. No canto superior do tela do Pin PAG ao iniciar tem o Numero 2.12 mais não sei se isto é a versão do Firmware.

**Comment by EmersonI22** [comment]
Muito obrigado pela ajuda Adriano, mas infelizmente não consegui resolver ainda.
Fiz os ajustes como sugerido app.Config coloquei “1” no value do Tef_PinPadQrCode
Estou desconfiado a versão do Firmware que você comentou. Mais não descobri ainda como obter esta informação. No canto superior do tela do Pin PAG ao iniciar tem o Numero 2.12 mais não sei se isto é a versão do Firmware.

**Comment by adrbarros** [comment]
Eu não tenho PinPads aqui com versão firmware 2.08 e/ou Superior para Testar (os 3 que tenho são 1.08a)
Mas tenho clientes em Produção Funcionando Perfeitamente o QrCode no PinPad. Seu PinPad PPC930 aparentemente suporta QrCode. Agora não sei te falar se no Modo SitefDemo da pra testar QrCode no PinPad. Vou tentar pegar emprestado um PinPad para realizar os testes.

Volto a dizer, em Produção funciona certinho.

Detalhe: Só para confirmar, no seu Clisitef.ini tem os Parametros 7 e 8
![image](https://user-images.githubusercontent.com/15065213/168081780-87702555-0848-42d2-a402-5219322bc80e.png)

**Comment by EmersonI22** [comment]
Boa tarde só para dar um retorno referente QRcode no PinPad para quem estiver com dificuldade.
Tem que ter todos os arquivos na pasta para funcionar. 
Se não vai dar nem erro. Hehehe.
CliSiTef32I.dll
libcurl32.dll
libemv.dll
RechargeRPC.dll
**QREncode32.dll => (QRCode no PinPad)**


Uma outra boa dica para os novatos é função (ObtencaoDadoAbertoPinpad = 789 )
'Código hexadecimal do dado do portador 2967 Entrada, por valor Código hexadecimal da mensagem que será exibida no PIN pad durante a coleta do dado. Verifique tabela a seguir. O dado pode conter zeros opcionais à esquerda. Ver observação descrita abaixo (1).
'Código hexadecimal do dado do portador     -   Mensagem exibida
'1-DIGITE O DDD; 2-REDIGITE O DDD; 3-DIGITE O TELEFONE; 4-REDIGITE O TELEFONE;
'5-DIGITE DDD+TELEFONE; 6-REDIGITE DDD+TELEFONE; 7-DIGITE O CPF;

_Outras questões:_

**1)**Alguém sabe como funciona o Banrisul?
Ele é um cartão de debito programável. O que eu tenho que informar para ele funcionar?

1:Cheque;**2:Cartao de Debito**;3:Cartao de Credito;4:Cartao Private Label;5:Confirmacao de Pre-autorizacao;6:Carteira Digital;

**1:Magnetico/Chip**;2:Digitado;

1:A Vista;2:Compra e Saque;**3:Pre-Datado**;4:Consulta parcelas CDC;5:CDC;

Forneca a data do Pre-datado. Enter assume 18/08/2022 (DDMMAAAA)
**26082022**

Data Invalida  do Pre-datado. Enter assume 18/08/2022 (DDMMAAAA)

_Fica em Loop não aceita a minha data nem a data que ele sugere._



**2)**Cartão Tricard, o cliente quer pagar a fatura pelo menu transações gerenciais. Já habilitei mais não aparece. Tem alguma dica?

CliSiTef.ini
[Geral]
TransacoesAdicionaisHabilitadas=3353: Menu Pagamento TriCard

**Comment by adrbarros** [comment]
Referente as outras Questoes:
- Não seu como funciona o Banrisul (Não tenho por aqui)
- Modulo Tricard para pagamento de faturas: o Modulo deve estar Instalado,
- 
Clisitef.ini
[Geral]
TransacoesAdicionaisHabilitadas=7;8;16;26;29;30;40;42;43;3014;3044;3047;3048;3055;3353;3515;
PermiteDebitoDigitado=1

**Comment by adrbarros** [comment]
Processo concluido

**Comment by lenonoliveira** [comment]
Alguém já conseguiu colocar um cartão de combustível como o Goodcard?

**Comment by adrbarros** [comment]
Único que já habilitei foi o Modulo Senff, no caso do Módulo GoodCard é bom dar uma ligada para a Adquente responsável para esse tipo de dívida, pois pode ter que habilitar algo la com eles

**Comment by lenonoliveira** [comment]
É ja fiz tudo, mas acredito que tem mais algo no CliSiTef.ini que precisa incluir. Já coloquei tanta coisa
