### ISSUE TITLE
Tratamento de desconto do Tipocampo == 4029

### ISSUE THREAD

**Issue by Marlonwg** [adrbarros/CliSitef#21]
- Esta transação deverá ser de 
R$ 80,00

- Para esta transação utilizar cartões Visa Electron e Visa

- Aplicação deve tratar que é retornado no TipoCampo=4029, seja exibido com a Finalizadora desconto antes da totalização da venda.

- A aplicação deverá somar os valores dos descontos recebidos e lança-los no cupom fiscal (valor inicial –valores dos descontos =valor da venda

Alguem ja implemento essa parte em C# sobre o desconto em cartao caso houver ?

**Comment by adrbarros** [comment]
Se não me engano, esse Desconto é do Cielo Premia, como não uso, não Homologuei na minha aplicação, e a homologação é Opcional deste recurso.

**Comment by Marlonwg** [comment]
E que ele esta aqui

![image](https://github.com/adrbarros/CliSitef/assets/58432414/4ba42288-0436-44db-b865-622f108513d7)


So que reamente nao vou utilizar somente a funcao 2 cartoes debito e credito sem troco e sem saque

**Comment by adrbarros** [comment]
Adicionado tratamento do TipoCampo 4029
