### ISSUE TITLE
Como faço para resgatar o NSU da transação?

### ISSUE THREAD

**Issue by dionathanbatista** [adrbarros/CliSitef#22]
Boa tarde
Primeiramente agradecer novamente pelo ótimo projeto.
Gostaria de saber como faço para pegar o NSU para conseguir gravar em um banco de dados e utilizar para emitir a NFCe 
Poderia me ajudar?

**Comment by adrbarros** [comment]
Dentro da Pasta TefRetorno, você tem todos os arquivos de Log das transações efetuadas (TefCrt_xxxxxx).
Esses Logs de transação, estão seguindo quase o padrão NTK (utilizados pelos Tef via troca de arquivos)
Assim o NSU Host esta na posição 012-000 do arquivo gerado
Dê uma olhada na pasta Documentos (zLeia_me-ArquivosGeradosTefRetorno.txt)
