### ISSUE TITLE
Pinpad não responde

### ISSUE THREAD

**Issue by WillCr2** [adrbarros/CliSitef#23]
Boa tarde!

Como faço para "reiniciar" o pinpad quando ele não responde?

Estou tentando fazer a coleta de dados utilizando a Função de leitura de campo aberto.
O fluxo está assim:
1.Inicia leitura de campo aberto no pinpad
2. Caso deseje cancelar a coleta de dados utilizo o parâmetro "interromper" = true (campo 23)
3. Se eu inicio novamente uma nova coleta de dados muito rápido(sem esperar o pinpad apagar a tela) então ele trava e não responde mais.

Tem alguma forma de quando o pinpad não responder, eu mandar uma reinicialização?

**Comment by adrbarros** [comment]
Olá, está fazendo isso pela aplicação de Demonstração?
Se sim, faça o passo a passo detalhado. Porquê, fiz teste tando na Aplicação de Demonstração e Também na minha Solução em Produção, e nenhuma travou o PinPad.

na Aplicação Demonstração, quando vc inicia a LeituraCampoAberto, onde vc pode interromper pela Tecla ESC ou pelo Botão Anula/Cancela no PinPad aparece uma Questionamento " Operação Cancelada?  SIM ou NÃO ", ai segue o Fluxo normal

**Comment by WillCr2** [comment]
Olá! 

Estou fazendo pela minha aplicação. Somente adaptei para funcionar com a sua DLL.

Perceba no vídeo que quando mando o comando de solicitar leitura de campo aberto para o pinpad, e em seguida cancelo essa solicitação (utilizo o campo 23 interromper = true) 
e se peço para iniciar novamente a requisição de leitura de campo aberto o pinpad não responde.

Percebi que isso acontece quando é muito rápido, parece que não da tempo de cancelar a solicitação anterior, e aí se perde...
Quando cancelo, se esperar a luz do pinpad apagar, então sempre funciona, mas se for muito rápido, note que a luz do pinpad continua ligada. 

Coloquei até o break point no continuar requisição, mas não estava chegando mais nada.
Utilizei o método de verificar se pinpad está ativo e mandei printar quando o sts != 1, igual no seu exemplo.


O meu problema é que isso é uma automação autoatendimento. Será sistema - cliente, sem ter alguém para auxiliar.

O Arduino que utilizo é para simular a chegada de um cliente. Estou tentando simular caso chegue cliente e saia, e em seguida volte rapidamente para o sensor. 


Upei um vídeo no drive para exemplificar.

https://drive.google.com/file/d/1xFe33x0LFsRib1_9Y-j-VSO0bGEXPhsv/view?usp=drive_link

**Comment by adrbarros** [comment]
Bom pelo Video não da pra ver mt coisa, mas toda interação com PinPad tem seu Fluxo, e que parece não estar obedecendo esse fluxo. Mas você tem que dar o Tempo para o Pinpad fazer a releitura e verificação
Nunca mexi com Arduino, mas tenho Totem de Autoatendimento, Self Checkout e todos funcionam perfeitamente

Fluxo é esse, o primeiro com ESC Precionado o Segundo com o Botao Anula/Cancela do PinPad

Passa pelo 23 constantemente, após comando ESC ou Anula o mesmo vai passar pelo 20 e fazer uma pergunta (Operação Cancelada?) em caso de SIM, o mesmo aborta, assim vc tem que verificar o Pinpad novamente, nesse momento vc poderia aguardar 1,5 segundos para fazer nova requisição

[Log20240527.txt](https://github.com/adrbarros/CliSitef/files/15458353/Log20240527.txt)

**Comment by WillCr2** [comment]
Entendi.

O que vou fazer é aguardar o tempo do pinpad. Colocar uma trava no sistema para não permitir que chame e cancele a chamado do pinpad toda hora. Porque desse jeito eu não estou respeitando o tempo de resposta do pinpad, por mais que seja rápido.

**Comment by adamsslz** [comment]
> Entendi.
> 
> O que vou fazer é aguardar o tempo do pinpad. Colocar uma trava no sistema para não permitir que chame e cancele a chamado do pinpad toda hora. Porque desse jeito eu não estou respeitando o tempo de resposta do pinpad, por mais que seja rápido.

ola! poderia me passar seu email pra poder tirar uma duvida ?

**Comment by adamslu38** [comment]
> Olá!
> 
> Estou fazendo pela minha aplicação. Somente adaptei para funcionar com a sua DLL.
> 
> Perceba no vídeo que quando mando o comando de solicitar leitura de campo aberto para o pinpad, e em seguida cancelo essa solicitação (utilizo o campo 23 interromper = true) e se peço para iniciar novamente a requisição de leitura de campo aberto o pinpad não responde.
> 
> Percebi que isso acontece quando é muito rápido, parece que não da tempo de cancelar a solicitação anterior, e aí se perde... Quando cancelo, se esperar a luz do pinpad apagar, então sempre funciona, mas se for muito rápido, note que a luz do pinpad continua ligada.
> 
> Coloquei até o break point no continuar requisição, mas não estava chegando mais nada. Utilizei o método de verificar se pinpad está ativo e mandei printar quando o sts != 1, igual no seu exemplo.
> 
> O meu problema é que isso é uma automação autoatendimento. Será sistema - cliente, sem ter alguém para auxiliar.
> 
> O Arduino que utilizo é para simular a chegada de um cliente. Estou tentando simular caso chegue cliente e saia, e em seguida volte rapidamente para o sensor.
> 
> Upei um vídeo no drive para exemplificar.
> 
> https://drive.google.com/file/d/1xFe33x0LFsRib1_9Y-j-VSO0bGEXPhsv/view?usp=drive_link


Ola williamtentei entrar com contato ctg pelo email e outras formas sem muito exito, assim que voce puder deixar teu contato poderia me tirar uma duvida ? irei enviar email pra vc .
