### ISSUE TITLE
Necessito de auxilio para iniciar

### ISSUE THREAD

**Issue by 98155100thp** [adrbarros/CliSitef#24]
Bom dia,
Ao executar o programa, está com o seguinte retorno "PinPad não encontrado".
Entretanto, estou com o SitDemo executando.

**Comment by adrbarros** [comment]
se estiver utilizando o Aplicação Demonstração, como está os seguintes arquivos:
Clisitef.ini
App.CliSiTef_DLL.exe.config

Clisitef.ini
[PinPadCompartilhado]
Porta=AUTO_USB

App.CliSiTef_DLL.exe.config
add key="Tef_PinPadPorta" value="AUTO_USB"

**Comment by 98155100thp** [comment]
Sim, estou usando a Aplicação Demonstração.

Estão desta mesma forma que passaste. 
Clisitef.ini
[PinPadCompartilhado]
Porta=AUTO_USB

App.CliSiTef_DLL.exe.config
add key="Tef_PinPadPorta" value="AUTO_USB"

![image](https://github.com/adrbarros/CliSitef/assets/28968071/83e4d7ba-bc30-4992-a8d4-ad00bdf63da5)

**Comment by adrbarros** [comment]
Não seu o que pode ser, então. Todas as vezes que tive erros de PinPad, o problema era o próprio (Trocava o Pinpad, e funcionava normalmente)

**Comment by 98155100thp** [comment]
o SiTef Demo simula um pinpad, confere? 
Pois não tenho a maquininha.

**Comment by adrbarros** [comment]
Sitef Demo, Simula o Ambiente para Transações.
Não Simula um Pinpad, para efetuar testes para Transações em Cartão você dever ter um Pinpad.
