### ISSUE TITLE
Como colocar imagem na tela do pinpad

### ISSUE THREAD

**Issue by WillCr2** [adrbarros/CliSitef#25]
Boa tarde!

A lib tem alguma função de apresentar imagem na telinha do pinpad?
verifiquei que é possível, mas gostaria de saber se já existe algo desenvolvido nessa lib.

**Comment by adrbarros** [comment]
Única imagem que vai para o Pinpad nessa implementação, é o QrCode do PIX (Desde que o pinpad esteja com firmaware 2.08 ou superior). Outros tipos de Imagens, Textos etc o PinPad deve estar habilitado com Protocolo ABECS.
Na Implementação, existe comunicação com o Protocolo ABECS, através da DLL Clisitef32I (Leitura de Campo Aberto), somente de Campos Tipo Texto
