### ISSUE TITLE
Não encontra DLL

### ISSUE THREAD

**Issue by UN-Software** [adrbarros/CliSitef#26]
Bom dia pessoal, tudo bem?

No momento que roda o projeto, ele diz não encontrar a DLL. Ela vai na raiz do DEBUG certo?

Obrigado,

Att

**Comment by adrbarros** [comment]
Olá.
as DLLs do [/src/ExternalLibraries/TEF_Demo_DLLs], dever sem copiadas para o Diretorio do EXE
