### ISSUE TITLE
Em producao

### ISSUE THREAD

**Issue by Marlonwg** [adrbarros/CliSitef#27]
Alguem ja esta utilizando em producao , Estranho que em homologacao funciona normalmente com o SITEF Demonstracao agora em producao nao gera nem a pasta logs no C: alguem ja passou por esse problema , outra coisa quando troco as dll's   <DllImport("CliSiTef32I.dll")>

nao sei porque nao funciona no caso

**Comment by adrbarros** [comment]
Bom, hoje instalação nova é tudo Sitef-Nuvem (até os cliente mais antigos que usam Sitef Local, eles estão migrando aos poucos para Nuvem).
Mas respondendo, eu uso em Produção desde 2013 o Sitef SofwareExpress. E para Ambiente de Produção, após Homologação, é só Substituir as DLLs do Sitef-Simulado para Sitef-Produção.
Hoje quem for o fornecedor do TEF (Ex.: SkyTEF), para cada PC que for utilizado o TEF, eles instaldam uma VPN para conexão com TEF, vão gerar um Código de Cliente que iria substituir no parametro Tef_Empresa, e o IP caso passem algum diferente de 127.0.0.1

[CliSiTef32I_Produção.zip](https://github.com/user-attachments/files/15890713/CliSiTef32I_Producao.zip)

**Comment by Marlonwg** [comment]
Realmente foi um erro base meu aqui estava utilizando a busca na pasta errada rsrs. E verdade hoje uso o TEF NUVEM na VPN esta bem pratico usar.

Obrigado
