### ISSUE TITLE
Cancelamento ou Confirmação de transações pendentes não esta funcionando

### ISSUE THREAD

**Issue by dionathanbatista** [adrbarros/CliSitef#28]
Boa tarde
Não canso de agradecer aqui pela biblioteca excelente.
Estou tendo problemas na homologação.
Ao fazer os testes previsto na documentação de pré-homologação me deparei com um problema ao cancelar ou confirmar as transações pendentes. Fiz como no documento, fiz a venda esperei dar como aprovada e desliguei o pc, e ao abrir o sistema fiz com que ele busca-se as transações pendentes e ela aparece corretamente mas quando tento cancelar ou confirmar ela não faz nada e volta aparecer quando fecho e abro o sistema.
ja vasculhei pra ver se encontro o problema mas não achei. será erro na dll?
outra coisa, ao abrir o menu administrativo eles exigem que tenha senha:

4º Código do Supervisor: O campo está sendo informado vazio. Sua aplicação possui algum login e senha para acessar as funções do menu administrativo, como Reimpressão e Cancelamento?
como faço para enviar a senha como eles estão pedindo ? obs.: ao abrir as funções administrativas o sistema já pede a senha e a verifica se é um usuário administrativo porem não sei como enviar a dll.
se puderem me ajudar agradeço?

**Comment by adrbarros** [comment]
![image](https://github.com/adrbarros/CliSitef/assets/15065213/aeb2dd04-d899-4269-afb1-5955aad8ace4)

Iniciando, Transações Pendentes Funcionando normalmente (Para a transação ficar pendente, nao deve ser executado o comando CNF, exemplo de como testar: Faça 1 transação de R$2,00, na confirmação do valor coloque R$1,00 como se fosse multiplos cartões, siga o fluxo até a transação ser aprovada. Nesse comento aborte a aplicação e quando reestabelecer a mesma, faça a verificação de transações pendentes.)

Senha de Usuario: 1ª Vez que vejo exigirem isso. Mas isso deve ser uma lógica sua ao abrir o menu Administrativo.
Tem um Botao (Senha 4 Dig) para confirmar no PinPad (Mas uso isso pra Clientes Confirmarem a senha quado vão fazer algum convênio ou crediário interno na Loja, exemplificação na Aplicação Leitura de Campo Aberto, e só funciona com PinPads que possuam criptografia ABECS)

**Comment by adrbarros** [comment]
Fiz um ajuste para captura do código do supervisor, ao acessar o Menu Adminstrativo pra Cancelamento de Transações, dê uma olhada pra  ver se é isso que estão exigindo (Caso nao defina nehuma senha por padrão é 1234)

**Comment by dionathanbatista** [comment]
Ok vou testar e verificar se passa na homologação
