### ISSUE TITLE
"Aguarde em processamento....." 2x e comprovantes 2x

### ISSUE THREAD

**Issue by UN-Software** [adrbarros/CliSitef#29]
Pessoal, uma dúvida...ele aparece "Aguarde em processamento....." e "Aguarde em processamento (35)" por duas vezes, e imprime dois comprovantes de finalização iguais. Isso é normal? Obrigado

**Comment by adrbarros** [comment]
Sim é normal as Mensagens e os Comprovantes, são sempre 2 Comprovantes, uma Via do Cliente e um Via do Estabelecimento.

**Comment by UN-Software** [comment]
Certo Adriano, obrigado

**Comment by adrbarros** [comment]
Olhar a Pasta Logs, para ver tudo que o Clisitef retorna
