### ISSUE TITLE
Captura dados do pinpad

### ISSUE THREAD

**Issue by elieltonbitencourt** [adrbarros/CliSitef#3]
Tem exemplo de como faz a captura do CPF do cliente por exemplo? vi que precisa iniciar uma requisição mandando 789, mas não consegui entender exatamente o fluxo das chamadas

**Comment by adrbarros** [comment]
// Na classe TefSoftwareExpress vai ter q Adicionar
[DllImport("CliSiTef32I.dll")]
private static extern int ObtemDadoPinPadDiretoEx(string ChaveAcesso, string Identificador, string Entrada, [MarshalAs(UnmanagedType.VBByRefStr)] ref string Saida);

public string CapturaCpfPinpad()
{
	string msg = new string(' ', 50);
        ObtemDadoPinPadDiretoEx("", "", "011111DIGITE CPF                      CONFIRME O CPF  ", ref msg);
	return msg.Substring(4, 11);
}

A partir da versão 6 do CliSiTef32I.dll, não é mais necessário ChaveAcesso e Identificador

**Comment by elieltonbitencourt** [comment]
que show, funcionou obrigado
