### ISSUE TITLE
Preciso fazer o teste de TLS como faço para usar IniciaFuncaoSiTefInterativo com TLS

### ISSUE THREAD

**Issue by dionathanbatista** [adrbarros/CliSitef#30]
Boa tarde
Na homologação estao solicitando que faço um teste de TLS.
Como passar as informacoes solicitadas no IniciaFuncaoSiTefInterativo?
Alguem teria um exemplo?

**Comment by adrbarros** [comment]
Tarde, Bom se olhar do Doc: 0-SiTef - Interface Simplificada com a aplicação(VRS-253).pdf, vai ver que a chamada é realizada apenas de uma forma, pois, o metodo é chamado por uma iteroperabilidade.
Assim, acredito que se o TLS estiver instalado no Windows, ja deve considerar uma chamada desse tipo, ou no caso de Produção a VPN já é habilidato TLS no Tunel criado.

Bom mas se tiver alguma configuração de TLS, creio que poderá ser em 2 lugares:
1 - ConfiguraIntSiTefInterativoEx (nos parametros Adicionais, da chamada deste métoto)
2 - Ou no Clisitef.ini

Particularmente eu não sei, porquê, pra mim isso nunca foi solicitado

**Comment by adrbarros** [comment]
https://dev.softwareexpress.com.br/docs/clisitef-interface-android/tls_transport_layer_security
Dê uma olhada a partir deste ponto (Porem diz que é para Interface Android)

**Comment by adrbarros** [comment]
Pelo que eu entendi, na leitura do Link acima, fiz alguns ajustes para essa configuração

**Comment by dionathanbatista** [comment]
Bom dia
Me enviaram esse documento
[Teste integração TLS Fiserv.docx](https://github.com/user-attachments/files/16332115/Teste.integracao.TLS.Fiserv.docx)

**Comment by adrbarros** [comment]
Ajustado
Adicionado na pasta \Documentos o arquivo -> CliSiTef - Projeto TLS - 1.05 .pdf

Esta configuração pose ser realizada no arquivo Clisitef.ini na seção [Geral] (Se for uma aplicação Desktop, recomento fazer no arquivo)
[Geral]
TipoComunicacaoExterna=TLSGWP
.... continuação

e Pode ser configurado no .config da Aplicação
- add key="Tef_TipoComunicacaoExterna" value="TLSGWP"

Assim ai fazer a chamada do ConfiguraIntSiTefInterativoEx, será passado nos parametros adicionais:
[TipoComunicacaoExterna=TLSGWP]

**Comment by dionathanbatista** [comment]
Baixei e testei novamente da forma que me explicou em ambos deu sem conexao com o servidor
![image](https://github.com/user-attachments/assets/96738870-a55e-491a-b6c7-6f23d47982b2)

**Comment by adrbarros** [comment]
é isso ai mesmo que deve acontecer para testar o TLS, está escrito no DOCX que você anexou PAG. 2 Item B, que vai retornar SEM CONEXAO COM SERVIDOR

**Comment by dionathanbatista** [comment]
entendi, mas mesmo eu colocando ou nao
[Geral]
TipoComunicacaoExterna=TLSGWP 
ele da como sem conexao. Então entenda-se que depois d teste com ConfiguraIntSiTefInterativoEx volto a usar ConfiguraIntSiTefInterativo

**Comment by adrbarros** [comment]
Seguinte, vc usa 1 das 2 opções, se vc Configurar no:
Clisitef.ini a diretiva TipoComunicacaoExterna=TLSGWP 
vc deixa o .config em branco add key="Tef_TipoComunicacaoExterna" value=""

Se vc optar por configurar no .Config, o Clisitef não deverá ter a diretiva TipoComunicacaoExterna

de Acordo com o DOCx, de qq forma que vc configurar, é para dar SEM CONEXAO, pq a conexão TLS só sera habilitada para Dispositivos Mobile com conexão Wi-fi
Leia o DOCx que vc anexou e o  \Documentos o arquivo -> CliSiTef - Projeto TLS - 1.05 .pdf
que vc vai entender

o TESTE para homologação é para dar SEM CONEXAO (Esse é o TESTE)

Depois vc NÃO vai mais usar em nenhuma das opções para configurações, para o restante da Homologação

**Comment by dionathanbatista** [comment]
Perfeita a explicação obrigado.
