### ISSUE TITLE
Reimpressao especifica cartao credito ou debito

### ISSUE THREAD

**Issue by dionathanbatista** [adrbarros/CliSitef#31]
Boa tarde
Ultimo detalhe da homologação.
Solicitaram uma impressão especifica de uma venda feita no cartão de credito.
A venda foi concluída com sucesso porem depois na reimpressão especifica ela da como "DOC Inexistente".
Já a reimpressão do Ultimo Comprovante imprimi normalmente.
Já fiz todas as configurações que eles me passaram e não consegui reimprimir. Verifiquei o código e aparentemente esta tudo ok.
Poderia me ajudar?

**Comment by adrbarros** [comment]
Testei aqui Re-Impressão e está tudo Normal, se for REDE DOC é o NSU HOST, se for Visa passando pela Cielo é o AUT

**Comment by dionathanbatista** [comment]
O meu ja testei de todo jeito e nao vai ... Eu uso o REDE DOC e uso o NSU HOST mas nao consegue encontrar o doc.

**Comment by adrbarros** [comment]
Bom, pode ser configurações do seu Ambiente Simulado (Quem instalou e configurou? Fez a leitura dos documentos referentes as configurações de cada Adquirente utilizada para o Ambiente Simulado? Habilitou as reimpressões no arquivo de configuração do Servidor do Ambiente Simulado?

![Reimpresso_Configuracao](https://github.com/user-attachments/assets/0a5cc6de-3b24-4a15-8c48-d6f7cb3ae2ba)

![Reimpressao_Rede_Cielo](https://github.com/user-attachments/assets/90b03ed1-d165-42f5-af62-9e22e542ef68)
Como comentei, no meu Ambiente e em Produção nos Clientes tudo funcionando perfeitamente

**Comment by dionathanbatista** [comment]
Bom dia
Sim ja fizemos tudo isso. o suporte tecnico da fiserv me ajudou nessa parte e validou cada configuração. Eles me pediram para desinstalar tudo e reinsta-lar ou testar em outra maquina do zero é o que vou fazer essa manha
