### ISSUE TITLE
Erro ao finalizar ou rejeitar transações pendentes

### ISSUE THREAD

**Issue by dionathanbatista** [adrbarros/CliSitef#32]
Boa noite
Fiz todos os testes que eles pediram mas me mandaram isso:

_"Boa tarde [@Dionathan Batista Donizetti](mailto:dionathanbatista@gmail.com)
Finalizamos a análise dos seus testes e identificamos erro o seguinte divergência.
Teste de tratamento de transações pendentes.

Agora esta enviando duas funções FinalizaFuncaoSiTefInterativo uma para finalizar a IniciaFuncaoSiTefInterativo da chamada da 130 e outra para a transação que ficou pendente.

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614) IniciaFuncaoSiTefInterativo

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614)    Modalidade = 130

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614)    Valor = [0,00]

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614)    CupomFiscal = [258297]

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614)    DataFiscal = [20240723]

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614)    Horario = [113238]

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614)    Operador = []

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614)    ParametrosAdicionais = []

 

 

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614) ContinuaFuncaoSiTefInterativo

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614)    Entrada = [Continua=0; TamBuf=20000]

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614)    Saida = [Cmd=0; TipoCampo=210; Min=0; Max=0]

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614)    Buffer = [1]

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614)    Retorno = 10000

 

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614) ContinuaFuncaoSiTefInterativo

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614)    Entrada = [Continua=0; TamBuf=20000]

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614)    Saida = [Cmd=0; TipoCampo=160; Min=0; Max=0]

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614)    Buffer = [230781279]

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614)    Retorno = 10000

 

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614) ContinuaFuncaoSiTefInterativo

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614)    Entrada = [Continua=0; TamBuf=20000]

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614)    Saida = [Cmd=0; TipoCampo=163; Min=0; Max=0]

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614)    Buffer = [20240723]

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614)    Retorno = 10000

 

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614) ContinuaFuncaoSiTefInterativo

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614)    Entrada = [Continua=0; TamBuf=20000]

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614)    Saida = [Cmd=0; TipoCampo=164; Min=0; Max=0]

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614)    Buffer = [112930]

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614)    Retorno = 10000

 

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614) ContinuaFuncaoSiTefInterativo

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614)    Entrada = [Continua=0; TamBuf=20000]

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614)    Saida = [Cmd=0; TipoCampo=161; Min=0; Max=0]

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614)    Buffer = [0]

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614)    Retorno = 10000

 

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614) ContinuaFuncaoSiTefInterativo

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614)    Entrada = [Continua=0; TamBuf=20000]

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614)    Saida = [Cmd=0; TipoCampo=211; Min=0; Max=0]

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614)    Buffer = [2]

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614)    Retorno = 10000

 

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614) ContinuaFuncaoSiTefInterativo

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614)    Entrada = [Continua=0; TamBuf=20000]

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614)    Saida = [Cmd=0; TipoCampo=1319; Min=0; Max=0]

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614)    Buffer = [600]

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614)    Retorno = 10000

 

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614) ContinuaFuncaoSiTefInterativo

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614)    Entrada = [Continua=0; TamBuf=20000]

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614)    Retorno = 0

 

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614) FinalizaFuncaoSiTefInterativo

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614)    Confirma = 1

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614)    CupomFiscal = [258297]

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614)    DataFiscal = [20240723]

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614)    Horario = [113238]

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614)    ParametrosAdicionais = []

 

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614) EscreveMensagemPermanentePinPad

11:32:38 - (00000000.IP000001, pid=15412, hnd=10590614)    MsgDisplay = [GDM AUTOMACAO COMERCIAL]

11:32:39 - (00000000.IP000001, pid=15412, hnd=10590614)    Retorno = 0

 

11:32:42 - (00000000.IP000001, pid=15412, hnd=10590614) FinalizaFuncaoSiTefInterativo

11:32:42 - (00000000.IP000001, pid=15412, hnd=10590614)    Confirma = 0

11:32:42 - (00000000.IP000001, pid=15412, hnd=10590614)    CupomFiscal = [230781279]

11:32:42 - (00000000.IP000001, pid=15412, hnd=10590614)    DataFiscal = [20240723]

11:32:42 - (00000000.IP000001, pid=15412, hnd=10590614)    Horario = [113242]

11:32:42 - (00000000.IP000001, pid=15412, hnd=10590614)    ParametrosAdicionais = []

 

 

Você só vai enviar a FinalizaFuncaoSiTefInterativo com os dados da transação que esta pendente.

Outro ponto é o TLS da fiserv.

Você fez o desenvolvimento ?"_

Ja vasculhei o codigo e nao encontrei nada de errado.
Poderia me ajudar?

**Comment by adrbarros** [comment]
Bom dia.
1ª Observação, A aplicação Demonstração tem o intuito para fins meio que didáticos, com exemplos dos processos passo a passo. Significa que em alguns momentos você não vai seguir a risca o que está implementado na Lib, um exemplo são as transações pendente. 

- Transações Pendentes:
Realmente, para homologação você deve Confirmar ou Cancelar de uma vez só Todas as Transações, chamando o FinalizaFuncaoSiTefInterativo apenas 1 vez.
No Exemplo da Aplicação Demonstração é retornado quantidade de transações pendentes, depois eu implementei para confirmar ou cancelar 1 a 1 dessas transações, afim de mostar os dados de cada transação.
Mas para Homologação você retorna a quantidade de transações e depois pergunta se quer Confirmar ou Cancelar, e esse último processo, vai ser realizado 1 vez somente para todas as transações pendentes.

- TLS
Apesar de ter colocado na chamada do ConfiguraIntSiTefInterativoEx, nem precisaria ter feito isso, porquê pode ser colocado os parametros TLSGWP direto no arquivo Config.ini e outros.
E como disse em mensagem anterior. A Conexão TLS em Ambiente Simulado NÃO vai funcionar, confirme esta escrito no documento, então o TESTE é colocar o parametro do TLS (Aconselho que seja no Config.ini), assim o TEF dar dar Erro de Conexão (e Esse é o TESTE)

![image](https://github.com/user-attachments/assets/6185c8cd-443a-4eb3-a0c5-483f9d920d3e)

**Comment by dionathanbatista** [comment]
Bom dia :)
Sim sim, me ajudou muito.
Consegui resolver aqui
Muito Obrigado.
