### ISSUE TITLE
Problema com Carteira Digital - Trn. nao habilitada

### ISSUE THREAD

**Issue by joanvitor** [adrbarros/CliSitef#4]
Olá, Adriano Barros

Meu nome é Joan Vitor, sou desenvolvedor C# Júnior, estou trabalhando em uma implementação de carteiras digitais (pix) na automação comercial através da sua biblioteca, juntamente com o [andrebts](https://github.com/andrebts).

Seguimos os seguintes passos:

- Instalado o SitDemo e o CardSE enviados pelo próprio suporte da Software Express.

- Seguidos os passos descritos no arquivo: [8-CardSE_PIX_Guia de Instalação.pdf](https://github.com/adrbarros/CliSitef/blob/master/Documentos/8-CardSE_PIX_Guia%20de%20Instala%C3%A7%C3%A3o.pdf)

  - Configurador Sitef -> Bin -> Estabelecimento

   ![image](https://user-images.githubusercontent.com/38784623/209218096-63d39c41-b899-45e5-a3f9-8ac67df9f171.png)

  - Configurador Sitef -> Bin -> Comunicação

  ![image](https://user-images.githubusercontent.com/38784623/209216399-193ffc03-ce46-4fa5-93b8-b881788a7618.png)

  - Carga de tabela do Bin

  ![image](https://user-images.githubusercontent.com/38784623/209216995-32a3004a-e644-4e25-9b2d-8ea4be5c8ffb.png)

  - Configurador Sitef -> CardSE -> Estabelecimento

  ![image](https://user-images.githubusercontent.com/38784623/209217158-881d20f6-d8b7-4652-8511-99b5cf6bd079.png)

  - Configurador Sitef -> CardSE -> Comunicação

  ![image](https://user-images.githubusercontent.com/38784623/209218416-1905d99f-84ba-4190-a1e3-e441dff4d91d.png)

  - Carga de tabela do CardSE

  ![image](https://user-images.githubusercontent.com/38784623/209218654-565a8dcc-8db7-4ecc-a473-fa42744a2c55.png)

  - No visualizador de tabela mostra que o pix está habilitado, como visto na imagem:

  ![image](https://user-images.githubusercontent.com/38784623/209195254-5e0b6fd0-3ac5-4deb-970e-1768c568bf18.png)

  - Versão do simcomu-s.exe

  ![image](https://user-images.githubusercontent.com/38784623/209218548-c265d991-36ba-4bc9-a481-8d2f6f21905b.png)

  - Versão da DLL do CliSiTef

  ![image](https://user-images.githubusercontent.com/38784623/209222044-7fe8447c-cc17-43f4-9a19-38ffb4acb517.png)

  - Conteúdo do arquivo `CliSiTef.ini`

  ![image](https://user-images.githubusercontent.com/38784623/209221570-338b0201-39de-4e60-a23f-bf8706994cdf.png)

Com o conhecimento atual da utilização de carteiras digitais no SiTef, acreditamos que executamos todos os passos de configuração necessários, entretanto ao selecionar `"CRT CD"` ou `"CRT" -> "Carteira digital"` na aplicação da biblioteca, é retornada a mensagem `"Carteira Digital - Trn. nao habilitada"`, conforme imagem abaixo:

  - Erro

  ![image](https://user-images.githubusercontent.com/38784623/209221430-af996b0d-c661-4f83-a533-b5cabe3bcd16.png)

Ao depurar percebemos que o último resultado das chamadas ao metódo `ContinuaFuncaoSiTefInterativo` retorna o valor -24 como visto no gif abaixo:

![DemoErroCarteiraDigital-24](https://user-images.githubusercontent.com/38784623/209223945-07651a7d-4434-4eed-8299-55efb17244f5.gif)

Não entendemos qual o problema para podermos solucioná-lo. Você já passou por essa situação? Há alguma outra configuração necessária além das mencionadas nesse issue?

**Comment by adrbarros** [comment]
Eu também, não ententi essa incosistencia no PIX em Ambiente Simulado (pra mim aqui ja tem quase 1 ano que não funciona). Nem o Suporte SoftwareExpress conseguiu resolver isso no meu Ambiente. Ai para testar Carteiras Digitais eu habilito o PicPay para as simulações (que para Simulação é o mesmo Conceito)

OBS1.: Em Ambiente Produção, o PIX, PicPay, Mercado Pago etc,  funcionam corretamente (desde que esteja configurado corretamente)

OBS2.: Estou fazendo um outro projeto para Integração PIX direto com a Instituição Financeira/Bancária, pois, acontece cada coisa com esse PIX junto ao Modulo CardSE que ninguém consegue explicar (Nem a SofwareExpresss). Exemplo: Cliente pagou sua compra finalizando com PIX, operação aprovada saem os comprovantes tudo rapido e certinho, ai passam 15 a 20 minutos aparece que a transação foi estornada pelo Módulo, e ninguém consegue explicar. Assim entram em contato com Suporte Software Express, eles conectam pegam os arquivos do Caixa para auditoria, ai num sei que jeito eles aprovam novamente a transação, mas não te explicam o que aconteceu.

**Comment by claudineibr** [comment]
Eu também tive um problema para configurar, tive ajuda do suporte, se quiser tentar segue esses passos, aqui funciona porém uso phyton

![image](https://user-images.githubusercontent.com/3764522/209345761-77a595f4-c4cc-4e32-a465-00dde32715d0.png)

No campo Endereço Host(IP ou domínio) adicionar o seguinte valor: 1.2.3.4 e no campo Port Tcp: 7010
![image](https://user-images.githubusercontent.com/3764522/209345832-b7b5c6d3-3326-42a7-aa2d-2b9090fcefce.png)


Configuração de Estabelecimento.

No campo Cod. Estabelecimento adicionar o seguinte valor: 008496898000142

Na caixa de seleção, clicar no checkbox  referente as carteiras que deseja habilitar.
Obs. Caso seja solicitado AccessToken, informar o seguinte código: 000000000000000

![image](https://user-images.githubusercontent.com/3764522/209345931-4c86ad44-1bfd-442c-895f-99cf24f2cbec.png)

![image](https://user-images.githubusercontent.com/3764522/209346016-3d45a1f7-911c-4b5c-884f-fb98e277e28b.png)

**Comment by adrbarros** [comment]
@claudineibr Obrigado pela dica. Vou configurar dessa forma e testar

**Comment by joanvitor** [comment]
Boa tarde, 

Gostariamos de agradecer a você @adrbarros e ao @claudineibr. Ambas as soluções funcionaram após a configuração. Obrigado! Sem a contribuição de vocês não estaria dando mais um passo. Agora, estou na fase de pré-homologação.
