### ISSUE TITLE
Migração .net 6

### ISSUE THREAD

**Issue by williamgueiros** [adrbarros/CliSitef#9]
Bom dia.

Posso tentar migrar o projeto para .net 6 lts.

Para podermos aumentar a longevidade do projeto.

**Comment by adrbarros** [comment]
Ola, saudações.

Fique a vontade para realizar as alterações.
Obs.: manter a compatibilidade com .Net Full Framework, para aqueles que ja utilizam o projeto como apoio nas implementações.
